
 CREATE TABLE TRIVIA_TABLE  (

  T_ID           INTEGER PRIMARY KEY NOT NULL AUTO_INCREMENT,
  T_QUESTION      VARCHAR(255) NOT NULL,
  T_ANSWER1      VARCHAR(30) NOT NULL,
  T_ANSWER2      VARCHAR(30) NOT NULL,
  T_ANSWER3      VARCHAR(30) NOT NULL,
  T_ANSWER4      VARCHAR(30) NOT NULL,
  T_ANSWER        VARCHAR(30) NOT NULL,
  T_COUNT          INTEGER ,
  T_IMG  LONGBLOB NOT NULL
  );
  